"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class AccessKeyRequestTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The name of the access key."""
    enabled: NotRequired[bool]
    r"""Whether the access key is enabled or disabled."""


class AccessKeyRequest(BaseModel):
    name: Optional[str] = None
    r"""The name of the access key."""

    enabled: Optional[bool] = None
    r"""Whether the access key is enabled or disabled."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
