"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accesskey import AccessKey, AccessKeyTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class AccessKeysResponseTypedDict(TypedDict):
    access_keys: NotRequired[List[AccessKeyTypedDict]]
    r"""The list of the access keys."""
    total: NotRequired[int]
    r"""Total number of the access keys."""


class AccessKeysResponse(BaseModel):
    access_keys: Optional[List[AccessKey]] = None
    r"""The list of the access keys."""

    total: Optional[int] = None
    r"""Total number of the access keys."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["access_keys", "total"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
