"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class APIAccessKeyTypedDict(TypedDict):
    r"""Brief details of a single API Access Key."""

    key: NotRequired[str]
    r"""The API key."""
    secret: NotRequired[str]
    r"""The API secret."""
    enabled: NotRequired[bool]
    r"""Whether the access key is enabled or disabled."""


class APIAccessKey(BaseModel):
    r"""Brief details of a single API Access Key."""

    key: Optional[str] = None
    r"""The API key."""

    secret: Optional[str] = None
    r"""The API secret."""

    enabled: Optional[bool] = None
    r"""Whether the access key is enabled or disabled."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["key", "secret", "enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
