"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .cloudassettypebreakdown import (
    CloudAssetTypeBreakdown,
    CloudAssetTypeBreakdownTypedDict,
)
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from datetime import date
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BreakdownTypedDict(TypedDict):
    r"""Usage breakdown by asset type and operation."""

    storage_image: NotRequired[float]
    r"""Storage usage for images."""
    storage_video: NotRequired[float]
    r"""Storage usage for videos."""
    storage_raw: NotRequired[float]
    r"""Storage usage for raw files."""
    transformations_image: NotRequired[float]
    r"""Transformation usage for images."""
    transformations_video: NotRequired[float]
    r"""Transformation usage for videos."""
    bandwidth_image: NotRequired[float]
    r"""Bandwidth usage for images."""
    bandwidth_video: NotRequired[float]
    r"""Bandwidth usage for videos."""
    bandwidth_raw: NotRequired[float]
    r"""Bandwidth usage for raw files."""
    image_impressions: NotRequired[float]
    r"""Number of times images were delivered (impressions)."""
    video_seconds: NotRequired[float]
    r"""Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio)."""


class Breakdown(BaseModel):
    r"""Usage breakdown by asset type and operation."""

    storage_image: Optional[float] = None
    r"""Storage usage for images."""

    storage_video: Optional[float] = None
    r"""Storage usage for videos."""

    storage_raw: Optional[float] = None
    r"""Storage usage for raw files."""

    transformations_image: Optional[float] = None
    r"""Transformation usage for images."""

    transformations_video: Optional[float] = None
    r"""Transformation usage for videos."""

    bandwidth_image: Optional[float] = None
    r"""Bandwidth usage for images."""

    bandwidth_video: Optional[float] = None
    r"""Bandwidth usage for videos."""

    bandwidth_raw: Optional[float] = None
    r"""Bandwidth usage for raw files."""

    image_impressions: Optional[float] = None
    r"""Number of times images were delivered (impressions)."""

    video_seconds: Optional[float] = None
    r"""Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "storage_image",
                "storage_video",
                "storage_raw",
                "transformations_image",
                "transformations_video",
                "bandwidth_image",
                "bandwidth_video",
                "bandwidth_raw",
                "image_impressions",
                "video_seconds",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CyclesTypedDict(TypedDict):
    from_day: NotRequired[date]
    r"""The start date of the billing cycle."""
    to_day: NotRequired[date]
    r"""The end date of the billing cycle."""
    usage: NotRequired[float]
    r"""Total usage for this cycle."""
    breakdown: NotRequired[BreakdownTypedDict]
    r"""Usage breakdown by asset type and operation."""
    product_environment_breakdown: NotRequired[List[CloudAssetTypeBreakdownTypedDict]]
    r"""Optional breakdown by product environment. May not be present in all responses."""


class Cycles(BaseModel):
    from_day: Optional[date] = None
    r"""The start date of the billing cycle."""

    to_day: Optional[date] = None
    r"""The end date of the billing cycle."""

    usage: Optional[float] = None
    r"""Total usage for this cycle."""

    breakdown: Optional[Breakdown] = None
    r"""Usage breakdown by asset type and operation."""

    product_environment_breakdown: Optional[List[CloudAssetTypeBreakdown]] = None
    r"""Optional breakdown by product environment. May not be present in all responses."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "from_day",
                "to_day",
                "usage",
                "breakdown",
                "product_environment_breakdown",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUsageResponseBreakdownTypedDict(TypedDict):
    r"""Usage breakdown by asset type and operation for the monthly cycle."""

    storage_image: NotRequired[float]
    r"""Storage usage for images."""
    storage_video: NotRequired[float]
    r"""Storage usage for videos."""
    storage_raw: NotRequired[float]
    r"""Storage usage for raw files."""
    transformations_image: NotRequired[float]
    r"""Transformation usage for images."""
    transformations_video: NotRequired[float]
    r"""Transformation usage for videos."""
    bandwidth_image: NotRequired[float]
    r"""Bandwidth usage for images."""
    bandwidth_video: NotRequired[float]
    r"""Bandwidth usage for videos."""
    bandwidth_raw: NotRequired[float]
    r"""Bandwidth usage for raw files."""
    image_impressions: NotRequired[float]
    r"""Number of times images were delivered (impressions)."""
    video_seconds: NotRequired[float]
    r"""Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio)."""


class BillingUsageResponseBreakdown(BaseModel):
    r"""Usage breakdown by asset type and operation for the monthly cycle."""

    storage_image: Optional[float] = None
    r"""Storage usage for images."""

    storage_video: Optional[float] = None
    r"""Storage usage for videos."""

    storage_raw: Optional[float] = None
    r"""Storage usage for raw files."""

    transformations_image: Optional[float] = None
    r"""Transformation usage for images."""

    transformations_video: Optional[float] = None
    r"""Transformation usage for videos."""

    bandwidth_image: Optional[float] = None
    r"""Bandwidth usage for images."""

    bandwidth_video: Optional[float] = None
    r"""Bandwidth usage for videos."""

    bandwidth_raw: Optional[float] = None
    r"""Bandwidth usage for raw files."""

    image_impressions: Optional[float] = None
    r"""Number of times images were delivered (impressions)."""

    video_seconds: Optional[float] = None
    r"""Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "storage_image",
                "storage_video",
                "storage_raw",
                "transformations_image",
                "transformations_video",
                "bandwidth_image",
                "bandwidth_video",
                "bandwidth_raw",
                "image_impressions",
                "video_seconds",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MonthlyCyclesTypedDict(TypedDict):
    from_day: NotRequired[date]
    r"""The start date of the monthly billing cycle."""
    to_day: NotRequired[date]
    r"""The end date of the monthly billing cycle."""
    usage: NotRequired[float]
    r"""Total usage for this monthly cycle."""
    breakdown: NotRequired[BillingUsageResponseBreakdownTypedDict]
    r"""Usage breakdown by asset type and operation for the monthly cycle."""
    product_environment_breakdown: NotRequired[List[CloudAssetTypeBreakdownTypedDict]]
    r"""Optional breakdown by product environment for the monthly cycle. May not be present in all responses."""


class MonthlyCycles(BaseModel):
    from_day: Optional[date] = None
    r"""The start date of the monthly billing cycle."""

    to_day: Optional[date] = None
    r"""The end date of the monthly billing cycle."""

    usage: Optional[float] = None
    r"""Total usage for this monthly cycle."""

    breakdown: Optional[BillingUsageResponseBreakdown] = None
    r"""Usage breakdown by asset type and operation for the monthly cycle."""

    product_environment_breakdown: Optional[List[CloudAssetTypeBreakdown]] = None
    r"""Optional breakdown by product environment for the monthly cycle. May not be present in all responses."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "from_day",
                "to_day",
                "usage",
                "breakdown",
                "product_environment_breakdown",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MetricUsageTypedDict(TypedDict):
    metric: NotRequired[str]
    r"""The type of metric being measured (e.g., \"credit\")."""
    limit: NotRequired[float]
    r"""The limit for this metric in the plan."""
    cycles: NotRequired[List[CyclesTypedDict]]
    r"""Full usage details per billing cycle (monthly or annual, depending on plan)."""
    monthly_cycles: NotRequired[List[MonthlyCyclesTypedDict]]
    r"""Monthly-level breakdown within a single annual cycle."""


class MetricUsage(BaseModel):
    metric: Optional[str] = None
    r"""The type of metric being measured (e.g., \"credit\")."""

    limit: Optional[float] = None
    r"""The limit for this metric in the plan."""

    cycles: Optional[List[Cycles]] = None
    r"""Full usage details per billing cycle (monthly or annual, depending on plan)."""

    monthly_cycles: Optional[List[MonthlyCycles]] = None
    r"""Monthly-level breakdown within a single annual cycle."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["metric", "limit", "cycles", "monthly_cycles"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BillingUsageResponseTypedDict(TypedDict):
    plan_name: NotRequired[str]
    r"""The name of the plan (e.g., \"Pro PAYG\", \"Advanced PAYG\")."""
    metric_usage: NotRequired[List[MetricUsageTypedDict]]


class BillingUsageResponse(BaseModel):
    plan_name: Optional[str] = None
    r"""The name of the plan (e.g., \"Pro PAYG\", \"Advanced PAYG\")."""

    metric_usage: Optional[List[MetricUsage]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["plan_name", "metric_usage"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
