"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel
import pydantic
from typing import Any, Dict
from typing_extensions import Annotated, TypedDict


class CedarSchemaResponseTypedDict(TypedDict):
    schema_: Dict[str, Any]


class CedarSchemaResponse(BaseModel):
    schema_: Annotated[Dict[str, Any], pydantic.Field(alias="schema")]


try:
    CedarSchemaResponse.model_rebuild()
except NameError:
    pass
