"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel
from typing_extensions import TypedDict


class CedarErrorTypedDict(TypedDict):
    cedar_message: str
    cedar_code: str


class CedarError(BaseModel):
    cedar_message: str

    cedar_code: str
