"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel
import pydantic
from typing_extensions import Annotated, TypedDict


class SchemaTypedDict(TypedDict):
    pass


class Schema(BaseModel):
    pass


class CedarSchemaResponseTypedDict(TypedDict):
    schema_: SchemaTypedDict


class CedarSchemaResponse(BaseModel):
    schema_: Annotated[Schema, pydantic.Field(alias="schema")]


try:
    CedarSchemaResponse.model_rebuild()
except NameError:
    pass
