"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CloudAssetTypeBreakdownTypedDict(TypedDict):
    storage_image: NotRequired[float]
    r"""Storage usage for images in this product environment."""
    storage_video: NotRequired[float]
    r"""Storage usage for videos in this product environment."""
    storage_raw: NotRequired[float]
    r"""Storage usage for raw files in this product environment."""
    transformations_image: NotRequired[float]
    r"""Transformation usage for images in this product environment."""
    transformations_video: NotRequired[float]
    r"""Transformation usage for videos in this product environment."""
    bandwidth_image: NotRequired[float]
    r"""Bandwidth usage for images in this product environment."""
    bandwidth_video: NotRequired[float]
    r"""Bandwidth usage for videos in this product environment."""
    bandwidth_raw: NotRequired[float]
    r"""Bandwidth usage for raw files in this product environment."""
    image_impressions: NotRequired[float]
    r"""Number of times images were delivered (impressions) in this product environment."""
    video_seconds: NotRequired[float]
    r"""Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio)."""
    cloud_name: NotRequired[str]
    r"""The name of the product environment."""


class CloudAssetTypeBreakdown(BaseModel):
    storage_image: Optional[float] = None
    r"""Storage usage for images in this product environment."""

    storage_video: Optional[float] = None
    r"""Storage usage for videos in this product environment."""

    storage_raw: Optional[float] = None
    r"""Storage usage for raw files in this product environment."""

    transformations_image: Optional[float] = None
    r"""Transformation usage for images in this product environment."""

    transformations_video: Optional[float] = None
    r"""Transformation usage for videos in this product environment."""

    bandwidth_image: Optional[float] = None
    r"""Bandwidth usage for images in this product environment."""

    bandwidth_video: Optional[float] = None
    r"""Bandwidth usage for videos in this product environment."""

    bandwidth_raw: Optional[float] = None
    r"""Bandwidth usage for raw files in this product environment."""

    image_impressions: Optional[float] = None
    r"""Number of times images were delivered (impressions) in this product environment."""

    video_seconds: Optional[float] = None
    r"""Video delivery usage measured in billing seconds (actual viewed duration multiplied by a resolution-based ratio)."""

    cloud_name: Optional[str] = None
    r"""The name of the product environment."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "storage_image",
                "storage_video",
                "storage_raw",
                "transformations_image",
                "transformations_video",
                "bandwidth_image",
                "bandwidth_video",
                "bandwidth_raw",
                "image_impressions",
                "video_seconds",
                "cloud_name",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
