"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import FieldMetadata, PathParamMetadata
from enum import Enum
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateUserGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class CreateUserGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateUserRole(str, Enum):
    r"""The role to assign."""

    MASTER_ADMIN = "master_admin"
    ADMIN = "admin"
    BILLING = "billing"
    TECHNICAL_ADMIN = "technical_admin"
    REPORTS = "reports"
    MEDIA_LIBRARY_ADMIN = "media_library_admin"
    MEDIA_LIBRARY_USER = "media_library_user"


class CreateUserRequestBodyTypedDict(TypedDict):
    r"""User details."""

    name: str
    r"""The user's name."""
    email: str
    r"""A unique email address, which serves as the login name and notification address."""
    role: NotRequired[CreateUserRole]
    r"""The role to assign."""
    sub_account_ids: NotRequired[List[str]]
    r"""A list of product environment IDs that this user can access. Ignored if the role is `master_admin`.
    **Default**: all product environments.

    """
    enabled: NotRequired[bool]
    r"""Whether the user is enabled. **Default**: true.

    """


class CreateUserRequestBody(BaseModel):
    r"""User details."""

    name: str
    r"""The user's name."""

    email: str
    r"""A unique email address, which serves as the login name and notification address."""

    role: Optional[CreateUserRole] = None
    r"""The role to assign."""

    sub_account_ids: Optional[List[str]] = None
    r"""A list of product environment IDs that this user can access. Ignored if the role is `master_admin`.
    **Default**: all product environments.

    """

    enabled: Optional[bool] = None
    r"""Whether the user is enabled. **Default**: true.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["role", "sub_account_ids", "enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
