"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class CustomPolicyTypedDict(TypedDict):
    policy_statement: str
    r"""A Cedar statement that permits or forbids a principal to perform an action on a resource. Refer to the [Permissions API guide](permissions_api_guide) for more information."""
    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""
    name: str
    r"""The name assigned to the policy."""
    description: NotRequired[Nullable[str]]
    r"""A short description of the policy."""
    scope_id: NotRequired[Nullable[str]]
    r"""The ID of a specific product environment, or \"all\" product environments, where the policy is applied. Required and only relevant if scope_type is \"prodenv\".
    - <product_environment_id>
    - all
    *Note:* The \"all\" specification is relevant only when creating or updating a policy.

    """
    enabled: NotRequired[Nullable[bool]]
    r"""Indicates whether the policy is currently active. Can be \"true\" (enabled) or \"false\" (disabled)."""


class CustomPolicy(BaseModel):
    policy_statement: str
    r"""A Cedar statement that permits or forbids a principal to perform an action on a resource. Refer to the [Permissions API guide](permissions_api_guide) for more information."""

    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    name: str
    r"""The name assigned to the policy."""

    description: OptionalNullable[str] = UNSET
    r"""A short description of the policy."""

    scope_id: OptionalNullable[str] = UNSET
    r"""The ID of a specific product environment, or \"all\" product environments, where the policy is applied. Required and only relevant if scope_type is \"prodenv\".
    - <product_environment_id>
    - all
    *Note:* The \"all\" specification is relevant only when creating or updating a policy.

    """

    enabled: OptionalNullable[bool] = True
    r"""Indicates whether the policy is currently active. Can be \"true\" (enabled) or \"false\" (disabled)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "scope_id", "enabled"])
        nullable_fields = set(["description", "scope_id", "enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
