"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class DeleteRoleGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class DeleteRoleGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class DeleteRoleRequestTypedDict(TypedDict):
    role_id: str
    r"""A unique identifier for the role."""
    force: NotRequired[bool]
    r"""Determines whether the role should be deleted when it has associated principals.
    - `true`: Deletes the role even if it has associated principals.
    - `false` (default): Prevents deletion if the role has associated principals. You must manually unassociate the principals before deleting the role.

    """


class DeleteRoleRequest(BaseModel):
    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A unique identifier for the role."""

    force: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Determines whether the role should be deleted when it has associated principals.
    - `true`: Deletes the role even if it has associated principals.
    - `false` (default): Prevents deletion if the role has associated principals. You must manually unassociate the principals before deleting the role.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["force"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
