"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .effectivepolicy import EffectivePolicy, EffectivePolicyTypedDict
from .principalrole import PrincipalRole, PrincipalRoleTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class DataTypedDict(TypedDict):
    principals: NotRequired[List[PrincipalRoleTypedDict]]
    custom_policies: NotRequired[List[EffectivePolicyTypedDict]]


class Data(BaseModel):
    principals: Optional[List[PrincipalRole]] = None

    custom_policies: Optional[List[EffectivePolicy]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["principals", "custom_policies"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EffectivePoliciesResponseTypedDict(TypedDict):
    data: NotRequired[DataTypedDict]


class EffectivePoliciesResponse(BaseModel):
    data: Optional[Data] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
