"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .effectivepolicy import EffectivePolicy, EffectivePolicyTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class EffectiveRoleTypedDict(TypedDict):
    id: NotRequired[str]
    r"""The unique identifier of the role."""
    system_policies: NotRequired[List[EffectivePolicyTypedDict]]
    r"""A list of all the predefined permission policies that are associated with this role."""


class EffectiveRole(BaseModel):
    id: Optional[str] = None
    r"""The unique identifier of the role."""

    system_policies: Optional[List[EffectivePolicy]] = None
    r"""A list of all the predefined permission policies that are associated with this role."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "system_policies"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
