"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetCustomPoliciesGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class GetCustomPoliciesGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetCustomPoliciesRequestTypedDict(TypedDict):
    scope_type: NotRequired[ScopeTypeEnum]
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""
    scope_id: NotRequired[str]
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\".
    - <product_environment_id>

    """
    enabled: NotRequired[Nullable[bool]]
    r"""Filter policies by enabled status (true/false)."""
    cursor: NotRequired[str]
    r"""A pagination cursor for fetching subsequent results."""


class GetCustomPoliciesRequest(BaseModel):
    scope_type: Annotated[
        Optional[ScopeTypeEnum],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""

    scope_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\".
    - <product_environment_id>

    """

    enabled: Annotated[
        OptionalNullable[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = UNSET
    r"""Filter policies by enabled status (true/false)."""

    cursor: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A pagination cursor for fetching subsequent results."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scope_type", "scope_id", "enabled", "cursor"])
        nullable_fields = set(["enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
