"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principaltypeenum import PrincipalTypeEnum
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetEffectivePoliciesGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class GetEffectivePoliciesGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetEffectivePoliciesRequestTypedDict(TypedDict):
    scope_type: NotRequired[ScopeTypeEnum]
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""
    scope_id: NotRequired[str]
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\".
    - <product_environment_id>

    """
    principal_type: NotRequired[PrincipalTypeEnum]
    r"""The type of principal you want to retrieve roles or permission policies for."""
    principal_id: NotRequired[str]
    r"""The unique identifier of the principal you want to retrieve roles or permission policies for.

    **Notes:**

    * This parameter is mandatory if `principal_type` is provided.
    * Ensure the specified ID belongs to a principle of the specified type.

    """


class GetEffectivePoliciesRequest(BaseModel):
    scope_type: Annotated[
        Optional[ScopeTypeEnum],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""

    scope_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\".
    - <product_environment_id>

    """

    principal_type: Annotated[
        Optional[PrincipalTypeEnum],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The type of principal you want to retrieve roles or permission policies for."""

    principal_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The unique identifier of the principal you want to retrieve roles or permission policies for.

    **Notes:**

    * This parameter is mandatory if `principal_type` is provided.
    * Ensure the specified ID belongs to a principle of the specified type.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["scope_type", "scope_id", "principal_type", "principal_id"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
