"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetProductEnvironmentsGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class GetProductEnvironmentsGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetProductEnvironmentsRequestTypedDict(TypedDict):
    enabled: NotRequired[bool]
    r"""Whether to only return enabled product environments (true) or disabled product environments (false).
    **Default**: all product environments are returned (both enabled and disabled).

    """
    ids: NotRequired[List[str]]
    r"""A list of up to 100 product environment IDs. When provided, other parameters are ignored."""
    cloud_names: NotRequired[List[str]]
    r"""A list of up to 100 product environment cloud names."""
    prefix: NotRequired[str]
    r"""Returns product environments where the name begins with the specified case-insensitive string."""


class GetProductEnvironmentsRequest(BaseModel):
    enabled: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Whether to only return enabled product environments (true) or disabled product environments (false).
    **Default**: all product environments are returned (both enabled and disabled).

    """

    ids: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A list of up to 100 product environment IDs. When provided, other parameters are ignored."""

    cloud_names: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""A list of up to 100 product environment cloud names."""

    prefix: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Returns product environments where the name begins with the specified case-insensitive string."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["enabled", "ids", "cloud_names", "prefix"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
