"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetRolePrincipalsGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class GetRolePrincipalsGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetRolePrincipalsRequestTypedDict(TypedDict):
    role_id: str
    r"""A unique identifier for the role."""
    scope_type: NotRequired[ScopeTypeEnum]
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""
    scope_id: NotRequired[str]
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\".
    - <product_environment_id>

    """
    verbose: NotRequired[bool]
    r"""Determines whether the response contains all the parameters described below (`true`), or only `id` and `principal_type` (`false`). *Default:* `false`"""
    folder_id: NotRequired[str]
    r"""* In the **Get role** endpoint, the specified `folder_id` is included in the `policy_statement` parameter of the response. If no `folder_id` is specified, the `policy_statement` shows a placeholder for the `folder_id` where relevant.
    * In the **Get a principal's roles**, **Get a role's principals**, and **Inspect** endpoints, the results are filtered by the specified `folder_id`. Only roles or principals with `policy_statement` parameters associated with that `folder_id` are returned.

    """
    asset_id: NotRequired[str]
    r"""Not currently supported."""
    collection_id: NotRequired[str]
    r"""* In the **Get role** endpoint, the specified `collection_id` is included in the `policy_statement` parameter of the response. If no `collection_id` is specified, the `policy_statement` shows a placeholder for the `collection_id` where relevant.
    * In the **Get a principal's roles** and **Get a role's principals** endpoints, the results are filtered by the specified `collection_id`. Only roles or principals with `policy_statement` parameters associated with that `collection_id` are returned.

    """
    param_key: NotRequired[List[str]]
    r"""The type of content instance the role applies to, either `folder_id` or `collection_id`. Use together with `param_value` to retrieve role assignments as they apply to a specific instance."""
    param_value: NotRequired[List[str]]
    r"""The ID of the content instance (for example, a specific folder or collection). Use together with param_key to retrieve roles as they apply to a specific instance."""


class GetRolePrincipalsRequest(BaseModel):
    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A unique identifier for the role."""

    scope_type: Annotated[
        Optional[ScopeTypeEnum],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""

    scope_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\".
    - <product_environment_id>

    """

    verbose: Annotated[
        Optional[bool],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Determines whether the response contains all the parameters described below (`true`), or only `id` and `principal_type` (`false`). *Default:* `false`"""

    folder_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""* In the **Get role** endpoint, the specified `folder_id` is included in the `policy_statement` parameter of the response. If no `folder_id` is specified, the `policy_statement` shows a placeholder for the `folder_id` where relevant.
    * In the **Get a principal's roles**, **Get a role's principals**, and **Inspect** endpoints, the results are filtered by the specified `folder_id`. Only roles or principals with `policy_statement` parameters associated with that `folder_id` are returned.

    """

    asset_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Not currently supported."""

    collection_id: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""* In the **Get role** endpoint, the specified `collection_id` is included in the `policy_statement` parameter of the response. If no `collection_id` is specified, the `policy_statement` shows a placeholder for the `collection_id` where relevant.
    * In the **Get a principal's roles** and **Get a role's principals** endpoints, the results are filtered by the specified `collection_id`. Only roles or principals with `policy_statement` parameters associated with that `collection_id` are returned.

    """

    param_key: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The type of content instance the role applies to, either `folder_id` or `collection_id`. Use together with `param_value` to retrieve role assignments as they apply to a specific instance."""

    param_value: Annotated[
        Optional[List[str]],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""The ID of the content instance (for example, a specific folder or collection). Use together with param_key to retrieve roles as they apply to a specific instance."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "scope_type",
                "scope_id",
                "verbose",
                "folder_id",
                "asset_id",
                "collection_id",
                "param_key",
                "param_value",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
