"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .permissiontypeenum import PermissionTypeEnum
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetSystemPoliciesGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class GetSystemPoliciesGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetSystemPoliciesRequestTypedDict(TypedDict):
    permission_type: NotRequired[PermissionTypeEnum]
    r"""Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID \"fg3841spr\")."""
    scope_type: NotRequired[ScopeTypeEnum]
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""


class GetSystemPoliciesRequest(BaseModel):
    permission_type: Annotated[
        Optional[PermissionTypeEnum],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies whether to retrieve roles whose permissions apply globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID \"fg3841spr\")."""

    scope_type: Annotated[
        Optional[ScopeTypeEnum],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Specifies the level for retrieving policies or roles, either at the account level or within product environments."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["permission_type", "scope_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
