"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principal import Principal, PrincipalTypedDict
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning import models
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import field_serializer, model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class InspectRequestPolicyParametersTypedDict(TypedDict):
    pass


class InspectRequestPolicyParameters(BaseModel):
    pass


class InspectRequestTypedDict(TypedDict):
    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""
    principals: List[PrincipalTypedDict]
    scope_id: NotRequired[str]
    policy_parameters: NotRequired[InspectRequestPolicyParametersTypedDict]
    cursor: NotRequired[str]


class InspectRequest(BaseModel):
    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    principals: List[Principal]

    scope_id: Optional[str] = None

    policy_parameters: Optional[InspectRequestPolicyParameters] = None

    cursor: Optional[str] = None

    @field_serializer("scope_type")
    def serialize_scope_type(self, value):
        if isinstance(value, str):
            try:
                return models.ScopeTypeEnum(value)
            except ValueError:
                return value
        return value

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scope_id", "policy_parameters", "cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
