"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class OperationEnum(str, Enum):
    r"""Specifies the operation to perform. Use `add` to associate or `remove` to disassociate."""

    ADD = "add"
    REMOVE = "remove"
