"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PermissionTypeEnum(str, Enum):
    r"""Specifies whether permissions apply globally or to specific content."""

    GLOBAL = "global"
    CONTENT = "content"
