"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principalrolesinspectdata import (
    PrincipalRolesInspectData,
    PrincipalRolesInspectDataTypedDict,
)
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PrincipalRolesInspectResponseDataTypedDict(TypedDict):
    principals: NotRequired[List[PrincipalRolesInspectDataTypedDict]]


class PrincipalRolesInspectResponseData(BaseModel):
    principals: Optional[List[PrincipalRolesInspectData]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["principals"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PrincipalRolesInspectResponseTypedDict(TypedDict):
    data: NotRequired[PrincipalRolesInspectResponseDataTypedDict]
    next_cursor: NotRequired[str]


class PrincipalRolesInspectResponse(BaseModel):
    data: Optional[PrincipalRolesInspectResponseData] = None

    next_cursor: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "next_cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
