"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principaltypeenum import PrincipalTypeEnum
from cloudinary_account_provisioning.types import BaseModel
from typing_extensions import TypedDict


class PrincipalTypedDict(TypedDict):
    type: PrincipalTypeEnum
    r"""The type of principal."""
    id: str
    r"""The unique identifier of the principal."""


class Principal(BaseModel):
    type: PrincipalTypeEnum
    r"""The type of principal."""

    id: str
    r"""The unique identifier of the principal."""
