"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .managementtypeenum import ManagementTypeEnum
from .permissiontypeenum import PermissionTypeEnum
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class PolicyParametersTypedDict(TypedDict):
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """


class PolicyParameters(BaseModel):
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """


class PrincipalRolesDataTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the role."""
    name: str
    r"""The name of the role."""
    management_type: ManagementTypeEnum
    r"""Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`)."""
    permission_type: PermissionTypeEnum
    r"""Specifies whether permissions apply globally or to specific content."""
    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""
    created_at: int
    r"""Creation time of the policy in epoch time."""
    updated_at: int
    r"""Last updated time of the policy in epoch time."""
    description: NotRequired[Nullable[str]]
    r"""A short description of the role."""
    scope_id: NotRequired[Nullable[str]]
    r"""Returned only if the scope type is product environment. Can be \"all\" to represent all product environments or an ID of a specific product environment."""
    policy_parameters: NotRequired[Nullable[PolicyParametersTypedDict]]
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """


class PrincipalRolesData(BaseModel):
    id: str
    r"""The unique identifier of the role."""

    name: str
    r"""The name of the role."""

    management_type: ManagementTypeEnum
    r"""Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`)."""

    permission_type: PermissionTypeEnum
    r"""Specifies whether permissions apply globally or to specific content."""

    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    created_at: int
    r"""Creation time of the policy in epoch time."""

    updated_at: int
    r"""Last updated time of the policy in epoch time."""

    description: OptionalNullable[str] = UNSET
    r"""A short description of the role."""

    scope_id: OptionalNullable[str] = UNSET
    r"""Returned only if the scope type is product environment. Can be \"all\" to represent all product environments or an ID of a specific product environment."""

    policy_parameters: OptionalNullable[PolicyParameters] = UNSET
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "scope_id", "policy_parameters"])
        nullable_fields = set(["description", "scope_id", "policy_parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
