"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class PrincipalTypeEnum(str, Enum):
    r"""The type of principal."""

    USER = "user"
    GROUP = "group"
    API_KEY = "apiKey"
    PROVISIONING_KEY = "provisioningKey"
