"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principaltypeenum import PrincipalTypeEnum
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PrincipalResponseDataPolicyParametersTypedDict(TypedDict):
    pass


class PrincipalResponseDataPolicyParameters(BaseModel):
    pass


class PrincipalResponseDataTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the principal."""
    type: PrincipalTypeEnum
    r"""The type of principal."""
    role_id: NotRequired[str]
    policy_parameters: NotRequired[PrincipalResponseDataPolicyParametersTypedDict]
    scope_type: NotRequired[ScopeTypeEnum]
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""
    scope_id: NotRequired[Nullable[str]]
    created_at: NotRequired[int]
    updated_at: NotRequired[int]


class PrincipalResponseData(BaseModel):
    id: str
    r"""The unique identifier of the principal."""

    type: PrincipalTypeEnum
    r"""The type of principal."""

    role_id: Optional[str] = None

    policy_parameters: Optional[PrincipalResponseDataPolicyParameters] = None

    scope_type: Optional[ScopeTypeEnum] = None
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    scope_id: OptionalNullable[str] = UNSET

    created_at: Optional[int] = None

    updated_at: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "role_id",
                "policy_parameters",
                "scope_type",
                "scope_id",
                "created_at",
                "updated_at",
            ]
        )
        nullable_fields = set(["scope_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
