"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principaltypeenum import PrincipalTypeEnum
from cloudinary_account_provisioning import models
from cloudinary_account_provisioning.types import BaseModel
from pydantic import field_serializer
from typing_extensions import TypedDict


class PrincipalTypedDict(TypedDict):
    type: PrincipalTypeEnum
    r"""The type of principal."""
    id: str
    r"""The unique identifier of the principal."""


class Principal(BaseModel):
    type: PrincipalTypeEnum
    r"""The type of principal."""

    id: str
    r"""The unique identifier of the principal."""

    @field_serializer("type")
    def serialize_type(self, value):
        if isinstance(value, str):
            try:
                return models.PrincipalTypeEnum(value)
            except ValueError:
                return value
        return value
