"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning import utils
from enum import Enum


class PrincipalTypeEnum(str, Enum, metaclass=utils.OpenEnumMeta):
    r"""The type of principal."""

    USER = "user"
    GROUP = "group"
    API_KEY = "apiKey"
    PROVISIONING_KEY = "provisioningKey"
