"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principalrolesdata import PrincipalRolesData, PrincipalRolesDataTypedDict
from .principaltypeenum import PrincipalTypeEnum
from cloudinary_account_provisioning.types import BaseModel
from typing import List
from typing_extensions import TypedDict


class PrincipalRolesInspectDataTypedDict(TypedDict):
    type: PrincipalTypeEnum
    r"""The type of principal."""
    id: str
    r"""The unique identifier of the principal."""
    roles: List[PrincipalRolesDataTypedDict]


class PrincipalRolesInspectData(BaseModel):
    type: PrincipalTypeEnum
    r"""The type of principal."""

    id: str
    r"""The unique identifier of the principal."""

    roles: List[PrincipalRolesData]
