"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .apiaccesskey import APIAccessKey, APIAccessKeyTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class ProductEnvironmentTypedDict(TypedDict):
    r"""Product Environment"""

    cloud_name: NotRequired[str]
    name: NotRequired[str]
    r"""The cloud name of the product environment."""
    enabled: NotRequired[bool]
    r"""Whether the product environment is enabled or disabled."""
    id: NotRequired[str]
    r"""The ID of the product environment."""
    api_access_keys: NotRequired[List[APIAccessKeyTypedDict]]
    r"""The list of the product environment's access keys."""
    created_at: NotRequired[datetime]
    r"""The date when the product environment was created."""
    updated_at: NotRequired[datetime]
    r"""The date when the product environment was last updated."""


class ProductEnvironment(BaseModel):
    r"""Product Environment"""

    cloud_name: Optional[str] = None

    name: Optional[str] = None
    r"""The cloud name of the product environment."""

    enabled: Optional[bool] = None
    r"""Whether the product environment is enabled or disabled."""

    id: Optional[str] = None
    r"""The ID of the product environment."""

    api_access_keys: Optional[List[APIAccessKey]] = None
    r"""The list of the product environment's access keys."""

    created_at: Optional[datetime] = None
    r"""The date when the product environment was created."""

    updated_at: Optional[datetime] = None
    r"""The date when the product environment was last updated."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "cloud_name",
                "name",
                "enabled",
                "id",
                "api_access_keys",
                "created_at",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
