"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CustomAttributesTypedDict(TypedDict):
    r"""Custom attributes associated with the product environment (optional)."""


class CustomAttributes(BaseModel):
    r"""Custom attributes associated with the product environment (optional)."""


class ProductEnvironmentRequestTypedDict(TypedDict):
    name: str
    r"""The display name for the product environment."""
    cloud_name: NotRequired[str]
    r"""The Cloudinary cloud name (optional, default is auto-generated)."""
    base_sub_account_id: NotRequired[str]
    r"""The ID of another product environment to copy settings from (optional)."""
    custom_attributes: NotRequired[CustomAttributesTypedDict]
    r"""Custom attributes associated with the product environment (optional)."""


class ProductEnvironmentRequest(BaseModel):
    name: str
    r"""The display name for the product environment."""

    cloud_name: Optional[str] = None
    r"""The Cloudinary cloud name (optional, default is auto-generated)."""

    base_sub_account_id: Optional[str] = None
    r"""The ID of another product environment to copy settings from (optional)."""

    custom_attributes: Optional[CustomAttributes] = None
    r"""Custom attributes associated with the product environment (optional)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["cloud_name", "base_sub_account_id", "custom_attributes"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
