"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ProductEnvironmentUpdateRequestCustomAttributesTypedDict(TypedDict):
    r"""Custom attributes associated with the product environment."""


class ProductEnvironmentUpdateRequestCustomAttributes(BaseModel):
    r"""Custom attributes associated with the product environment."""


class ProductEnvironmentUpdateRequestTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The display name for the product environment."""
    cloud_name: NotRequired[str]
    r"""The Cloudinary cloud name. An error is returned if the requested name already exists.
    **Note**: Can only be changed for accounts with fewer than 1000 images.

    """
    custom_attributes: NotRequired[
        ProductEnvironmentUpdateRequestCustomAttributesTypedDict
    ]
    r"""Custom attributes associated with the product environment."""
    enabled: NotRequired[bool]
    r"""Whether the product environment is enabled. **Default**: true.

    """


class ProductEnvironmentUpdateRequest(BaseModel):
    name: Optional[str] = None
    r"""The display name for the product environment."""

    cloud_name: Optional[str] = None
    r"""The Cloudinary cloud name. An error is returned if the requested name already exists.
    **Note**: Can only be changed for accounts with fewer than 1000 images.

    """

    custom_attributes: Optional[ProductEnvironmentUpdateRequestCustomAttributes] = None
    r"""Custom attributes associated with the product environment."""

    enabled: Optional[bool] = None
    r"""Whether the product environment is enabled. **Default**: true.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "cloud_name", "custom_attributes", "enabled"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
