"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .managementtypeenum import ManagementTypeEnum
from .scopetypeenum import ScopeTypeEnum
from .systempolicyresponsedata import (
    SystemPolicyResponseData,
    SystemPolicyResponseDataTypedDict,
)
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RoleResponseData1TypedDict(TypedDict):
    id: str
    r"""The unique identifier of the role."""
    name: str
    r"""The name of the role."""
    management_type: ManagementTypeEnum
    r"""Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`)."""
    permission_type: str
    r"""Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID \"fg3841spr\").

    - global

    - content

    """
    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""
    created_at: int
    r"""The permission policy creation timestamp in epoch time."""
    updated_at: int
    r"""The permission policy last updated timestamp in epoch time."""
    policies: NotRequired[List[SystemPolicyResponseDataTypedDict]]
    description: NotRequired[Nullable[str]]
    r"""A short description of the role."""
    policy_parameters: NotRequired[List[str]]
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """


class RoleResponseData1(BaseModel):
    id: str
    r"""The unique identifier of the role."""

    name: str
    r"""The name of the role."""

    management_type: ManagementTypeEnum
    r"""Specifies whether the role's policies are managed by Cloudinary (`system`) or by the user (`custom`)."""

    permission_type: str
    r"""Specifies whether the permission applies globally across all contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID \"fg3841spr\").

    - global

    - content

    """

    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    created_at: int
    r"""The permission policy creation timestamp in epoch time."""

    updated_at: int
    r"""The permission policy last updated timestamp in epoch time."""

    policies: Optional[List[SystemPolicyResponseData]] = None

    description: OptionalNullable[str] = UNSET
    r"""A short description of the role."""

    policy_parameters: Optional[List[str]] = None
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["policies", "description", "policy_parameters"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class RoleResponseTypedDict(TypedDict):
    data: NotRequired[RoleResponseData1TypedDict]


class RoleResponse(BaseModel):
    data: Optional[RoleResponseData1] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
