"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RoleToManagePolicyParametersTypedDict(TypedDict):
    r"""Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar)."""


class RoleToManagePolicyParameters(BaseModel):
    r"""Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar)."""


class RoleToManageTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the role you want to assign."""
    scope_id: NotRequired[str]
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\"."""
    policy_parameters: NotRequired[RoleToManagePolicyParametersTypedDict]
    r"""Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar)."""


class RoleToManage(BaseModel):
    id: str
    r"""The unique identifier of the role you want to assign."""

    scope_id: Optional[str] = None
    r"""The ID of a specific product environment where the policy is applied. This parameter is only relevant if `scope_type` is \"prodenv\"."""

    policy_parameters: Optional[RoleToManagePolicyParameters] = None
    r"""Defines the content instance that the role applies to. Specify the content type (`folder_id` or `collection_id`) and its corresponding ID. For example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar)."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scope_id", "policy_parameters"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
