"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class RoleTypedDict(TypedDict):
    name: str
    r"""The name of the role."""
    description: NotRequired[Nullable[str]]
    r"""A short description of the role."""
    system_policy_ids: NotRequired[List[str]]
    r"""A list of system permission policy IDs to be included in the role.

    **Tip:** Get the list of all available predefined policies using the [Get system policies](#tag/policies/get/policies) method.

    """


class Role(BaseModel):
    name: str
    r"""The name of the role."""

    description: OptionalNullable[str] = UNSET
    r"""A short description of the role."""

    system_policy_ids: Optional[List[str]] = None
    r"""A list of system permission policy IDs to be included in the role.

    **Tip:** Get the list of all available predefined policies using the [Get system policies](#tag/policies/get/policies) method.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["description", "system_policy_ids"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
