"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum


class ScopeTypeEnum(str, Enum):
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    ACCOUNT = "account"
    PRODENV = "prodenv"
