"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .scopetypeenum import ScopeTypeEnum
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SystemPolicyResponseDataTypedDict(TypedDict):
    id: str
    r"""The unique identifier of the policy."""
    name: str
    r"""The name of the policy"""
    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""
    policy_statement: str
    r"""A Cedar policy that permits or forbids a certain action on a certain element to a principal (user, group, or API key)."""
    created_at: int
    r"""Creation time of the policy in epoch time."""
    updated_at: int
    r"""Last update time of the policy in epoch time."""
    description: NotRequired[Nullable[str]]
    r"""A short description of the policy."""
    permission_type: NotRequired[str]
    r"""Specifies whether the permission applies globally across all resources or contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID \"fg3841spr\").

    - global

    - content

    """
    policy_parameters: NotRequired[List[str]]
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """
    category: NotRequired[str]
    r"""The category of the policy."""
    sub_category: NotRequired[str]
    r"""The sub-category of the policy."""


class SystemPolicyResponseData(BaseModel):
    id: str
    r"""The unique identifier of the policy."""

    name: str
    r"""The name of the policy"""

    scope_type: ScopeTypeEnum
    r"""Specifies where the role/policy is applied, either at the account level or within product environments."""

    policy_statement: str
    r"""A Cedar policy that permits or forbids a certain action on a certain element to a principal (user, group, or API key)."""

    created_at: int
    r"""Creation time of the policy in epoch time."""

    updated_at: int
    r"""Last update time of the policy in epoch time."""

    description: OptionalNullable[str] = UNSET
    r"""A short description of the policy."""

    permission_type: Optional[str] = None
    r"""Specifies whether the permission applies globally across all resources or contexts within the scope (i.e., security settings for the account, or all folders in a product environment), or specifically to designated content instances (i.e., folder with external ID \"fg3841spr\").

    - global

    - content

    """

    policy_parameters: Optional[List[str]] = None
    r"""For roles with `permission_type` set to `content`, this defines the type of content the role's policies apply to:
    - The content type can be: `folder_id` or `collection_id`.
    - When assigning the role, provide the instance, e.g. `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement` (Cedar).

    """

    category: Optional[str] = None
    r"""The category of the policy."""

    sub_category: Optional[str] = None
    r"""The sub-category of the policy."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "description",
                "permission_type",
                "policy_parameters",
                "category",
                "sub_category",
            ]
        )
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
