"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .systempolicyresponsedata import (
    SystemPolicyResponseData,
    SystemPolicyResponseDataTypedDict,
)
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class SystemPoliciesResponseTypedDict(TypedDict):
    data: NotRequired[List[SystemPolicyResponseDataTypedDict]]
    r"""An array of system policies."""
    next_cursor: NotRequired[str]
    r"""When a request has more results to return, the next_cursor value is returned as part of the response. You can then specify this value as the cursor parameter of a following request."""


class SystemPoliciesResponse(BaseModel):
    data: Optional[List[SystemPolicyResponseData]] = None
    r"""An array of system policies."""

    next_cursor: Optional[str] = None
    r"""When a request has more results to return, the next_cursor value is returned as part of the response. You can then specify this value as the cursor parameter of a following request."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "next_cursor"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
