"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel
from typing import Any, Dict
from typing_extensions import TypedDict


class SystemRolesAndPoliciesCatalogResponseTypedDict(TypedDict):
    catalog: Dict[str, Any]


class SystemRolesAndPoliciesCatalogResponse(BaseModel):
    catalog: Dict[str, Any]
