"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .updateroleprincipalsrequest import (
    UpdateRolePrincipalsRequest,
    UpdateRolePrincipalsRequestTypedDict,
)
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateRolePrincipalsGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class UpdateRolePrincipalsGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateRolePrincipalsRequest1TypedDict(TypedDict):
    role_id: str
    r"""A unique identifier for the role."""
    update_role_principals_request: UpdateRolePrincipalsRequestTypedDict
    r"""Principals details."""


class UpdateRolePrincipalsRequest1(BaseModel):
    role_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""A unique identifier for the role."""

    update_role_principals_request: Annotated[
        UpdateRolePrincipalsRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Principals details."""
