"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .accesskeyupdaterequest import (
    AccessKeyUpdateRequest,
    AccessKeyUpdateRequestTypedDict,
)
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from cloudinary_account_provisioning.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateAccessKeyGlobalsTypedDict(TypedDict):
    account_id: NotRequired[str]
    r"""Account ID"""


class UpdateAccessKeyGlobals(BaseModel):
    account_id: Annotated[
        Optional[str],
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ] = None
    r"""Account ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["account_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateAccessKeyRequestTypedDict(TypedDict):
    sub_account_id: str
    r"""The ID of the product environment."""
    key: str
    r"""The access key (api key)."""
    access_key_update_request: AccessKeyUpdateRequestTypedDict
    r"""Access key details for update."""


class UpdateAccessKeyRequest(BaseModel):
    sub_account_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The ID of the product environment."""

    key: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The access key (api key)."""

    access_key_update_request: Annotated[
        AccessKeyUpdateRequest,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
    r"""Access key details for update."""
