"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .operationenum import OperationEnum
from .updateroleprincipal import UpdateRolePrincipal, UpdateRolePrincipalTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UpdateRolePrincipalsRequestTypedDict(TypedDict):
    operation: NotRequired[OperationEnum]
    r"""Specifies the operation to perform. Use `add` to associate or `remove` to disassociate."""
    principals: NotRequired[List[UpdateRolePrincipalTypedDict]]


class UpdateRolePrincipalsRequest(BaseModel):
    operation: Optional[OperationEnum] = None
    r"""Specifies the operation to perform. Use `add` to associate or `remove` to disassociate."""

    principals: Optional[List[UpdateRolePrincipal]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["operation", "principals"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
