"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .principaltypeenum import PrincipalTypeEnum
from cloudinary_account_provisioning.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateRolePrincipalPolicyParametersTypedDict(TypedDict):
    r"""For roles with `permission_type` set to `content`, provide the ID of the specific folder or collection you want the role to apply to, for example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement`, written in Cedar language."""


class UpdateRolePrincipalPolicyParameters(BaseModel):
    r"""For roles with `permission_type` set to `content`, provide the ID of the specific folder or collection you want the role to apply to, for example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement`, written in Cedar language."""


class UpdateRolePrincipalTypedDict(TypedDict):
    principal_type: PrincipalTypeEnum
    r"""The type of principal."""
    principal_id: str
    r"""The unique identifier of the principal."""
    scope_id: NotRequired[Nullable[str]]
    r"""The ID of a specific product environment where the role is applied. This parameter is only relevant if `scope_type` is \"prodenv\"."""
    policy_parameters: NotRequired[UpdateRolePrincipalPolicyParametersTypedDict]
    r"""For roles with `permission_type` set to `content`, provide the ID of the specific folder or collection you want the role to apply to, for example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement`, written in Cedar language."""


class UpdateRolePrincipal(BaseModel):
    principal_type: PrincipalTypeEnum
    r"""The type of principal."""

    principal_id: str
    r"""The unique identifier of the principal."""

    scope_id: OptionalNullable[str] = UNSET
    r"""The ID of a specific product environment where the role is applied. This parameter is only relevant if `scope_type` is \"prodenv\"."""

    policy_parameters: Optional[UpdateRolePrincipalPolicyParameters] = None
    r"""For roles with `permission_type` set to `content`, provide the ID of the specific folder or collection you want the role to apply to, for example, `{\"folder_id\":\"asdfjkl12347890\"}`. This specification is passed to the `policy_statement`, written in Cedar language."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["scope_id", "policy_parameters"])
        nullable_fields = set(["scope_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
