"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .usergroupuser import UserGroupUser, UserGroupUserTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UserGroupTypedDict(TypedDict):
    r"""User group."""

    id: NotRequired[str]
    r"""The user group's ID."""
    name: NotRequired[str]
    r"""The user group's name."""
    users: NotRequired[List[UserGroupUserTypedDict]]
    r"""A list of user group users.
    Only returned in extended_details.

    """
    created_at: NotRequired[datetime]
    r"""The date when the user group was created.
    Only returned in extended_details.

    """
    updated_at: NotRequired[datetime]
    r"""The date when the user group was last updated.
    Only returned in extended_details.

    """


class UserGroup(BaseModel):
    r"""User group."""

    id: Optional[str] = None
    r"""The user group's ID."""

    name: Optional[str] = None
    r"""The user group's name."""

    users: Optional[List[UserGroupUser]] = None
    r"""A list of user group users.
    Only returned in extended_details.

    """

    created_at: Optional[datetime] = None
    r"""The date when the user group was created.
    Only returned in extended_details.

    """

    updated_at: Optional[datetime] = None
    r"""The date when the user group was last updated.
    Only returned in extended_details.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "users", "created_at", "updated_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
