"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .usergroupsummary import UserGroupSummary, UserGroupSummaryTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UserGroupsListResponseTypedDict(TypedDict):
    groups: NotRequired[List[UserGroupSummaryTypedDict]]
    r"""A list of user groups that the user belongs to."""


class UserGroupsListResponse(BaseModel):
    groups: Optional[List[UserGroupSummary]] = None
    r"""A list of user groups that the user belongs to."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["groups"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
