"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from datetime import datetime
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class EmailPreferencesTypedDict(TypedDict):
    r"""The user's email preferences."""


class EmailPreferences(BaseModel):
    r"""The user's email preferences."""


class UserTypedDict(TypedDict):
    r"""User details."""

    id: NotRequired[str]
    r"""The user's ID."""
    name: NotRequired[str]
    r"""The user's name."""
    first_name: NotRequired[str]
    r"""The user's first name."""
    last_name: NotRequired[str]
    r"""The user's last name."""
    role: NotRequired[str]
    r"""The user's role."""
    email: NotRequired[str]
    r"""The user's email."""
    pending: NotRequired[bool]
    r"""Whether the user is pending."""
    enabled: NotRequired[bool]
    r"""Whether the user is enabled."""
    created_at: NotRequired[datetime]
    r"""The date when the user was created."""
    updated_at: NotRequired[datetime]
    r"""The date when the user was last updated."""
    last_login: NotRequired[datetime]
    r"""The date when the user was last logged in."""
    all_sub_accounts: NotRequired[bool]
    providers: NotRequired[List[str]]
    r"""The list of authentication providers for the user."""
    email_preferences: NotRequired[EmailPreferencesTypedDict]
    r"""The user's email preferences."""
    account_id: NotRequired[str]
    r"""The account ID."""
    two_factor: NotRequired[bool]
    r"""Whether two-factor authentication is enabled."""
    status: NotRequired[str]
    r"""The user's status."""
    root: NotRequired[bool]
    r"""Whether the user is a root user."""
    technical_role: NotRequired[str]
    r"""The user's technical role."""
    group_count: NotRequired[int]
    r"""The number of groups the user belongs to."""
    sub_account_count: NotRequired[int]
    r"""The number of sub-accounts the user has access to."""


class User(BaseModel):
    r"""User details."""

    id: Optional[str] = None
    r"""The user's ID."""

    name: Optional[str] = None
    r"""The user's name."""

    first_name: Optional[str] = None
    r"""The user's first name."""

    last_name: Optional[str] = None
    r"""The user's last name."""

    role: Optional[str] = None
    r"""The user's role."""

    email: Optional[str] = None
    r"""The user's email."""

    pending: Optional[bool] = None
    r"""Whether the user is pending."""

    enabled: Optional[bool] = None
    r"""Whether the user is enabled."""

    created_at: Optional[datetime] = None
    r"""The date when the user was created."""

    updated_at: Optional[datetime] = None
    r"""The date when the user was last updated."""

    last_login: Optional[datetime] = None
    r"""The date when the user was last logged in."""

    all_sub_accounts: Optional[bool] = None

    providers: Optional[List[str]] = None
    r"""The list of authentication providers for the user."""

    email_preferences: Optional[EmailPreferences] = None
    r"""The user's email preferences."""

    account_id: Optional[str] = None
    r"""The account ID."""

    two_factor: Optional[bool] = None
    r"""Whether two-factor authentication is enabled."""

    status: Optional[str] = None
    r"""The user's status."""

    root: Optional[bool] = None
    r"""Whether the user is a root user."""

    technical_role: Optional[str] = None
    r"""The user's technical role."""

    group_count: Optional[int] = None
    r"""The number of groups the user belongs to."""

    sub_account_count: Optional[int] = None
    r"""The number of sub-accounts the user has access to."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "first_name",
                "last_name",
                "role",
                "email",
                "pending",
                "enabled",
                "created_at",
                "updated_at",
                "last_login",
                "all_sub_accounts",
                "providers",
                "email_preferences",
                "account_id",
                "two_factor",
                "status",
                "root",
                "technical_role",
                "group_count",
                "sub_account_count",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
