"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserGroupRequestTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The user group's name."""
    extended_details: NotRequired[bool]
    r"""Whether to only return extended (true) or basic information about the group (false).
    **Default**: false.

    """


class UserGroupRequest(BaseModel):
    name: Optional[str] = None
    r"""The user group's name."""

    extended_details: Optional[bool] = None
    r"""Whether to only return extended (true) or basic information about the group (false).
    **Default**: false.

    """

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "extended_details"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
