"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .usergroup import UserGroup, UserGroupTypedDict
from cloudinary_account_provisioning.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UserGroupsResponseTypedDict(TypedDict):
    user_groups: NotRequired[List[UserGroupTypedDict]]
    r"""A list of user groups."""


class UserGroupsResponse(BaseModel):
    user_groups: Optional[List[UserGroup]] = None
    r"""A list of user groups."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["user_groups"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
