"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from cloudinary_account_provisioning import models, utils
from cloudinary_account_provisioning._hooks import HookContext
from cloudinary_account_provisioning.types import OptionalNullable, UNSET
from cloudinary_account_provisioning.utils import get_security_from_env
from cloudinary_account_provisioning.utils.unmarshal_json_response import (
    unmarshal_json_response,
)
from typing import Any, List, Mapping, Optional


class BillingUsage(BaseSDK):
    def get(
        self,
        *,
        year: Optional[int] = None,
        include_prodenv_breakdown: Optional[bool] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.BillingUsageResponse]:
        r"""Get billing usage information

        Retrieve billing usage metrics for your account and product environments,
        including storage, bandwidth, impressions, and transformations.

        If `year` is provided:
        - **Annual subscription**: Returns the single annual usage cycle that began in the specified year (if any).
        - **Monthly subscription**: Returns all monthly usage cycles that began in the specified year.

        If `year` is not provided:
        - Returns usage for the year in which the current active subscription period began.
        - If no active subscription exists, an empty list is returned.

        **Note**: Usage metrics are updated daily, so calling this endpoint once per day gives you the latest data.


        :param year: The year to retrieve billing usage for. Behavior depends on subscription type (see above).
        :param include_prodenv_breakdown: Whether to include usage details by product environment. **Default**: false.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetBillingUsageRequest(
            year=year,
            include_prodenv_breakdown=include_prodenv_breakdown,
        )

        req = self._build_request(
            method="GET",
            path="/v1_1/provisioning/accounts/{account_id}/billing_usage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=models.GetBillingUsageGlobals(
                account_id=self.sdk_configuration.globals.account_id,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = self.do_request(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getBillingUsage",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "429", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(List[models.BillingUsageResponse], http_res)
        if utils.match_response(
            http_res, ["400", "401", "403", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = utils.stream_to_text(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)

    async def get_async(
        self,
        *,
        year: Optional[int] = None,
        include_prodenv_breakdown: Optional[bool] = None,
        retries: OptionalNullable[utils.RetryConfig] = UNSET,
        server_url: Optional[str] = None,
        timeout_ms: Optional[int] = None,
        http_headers: Optional[Mapping[str, str]] = None,
    ) -> List[models.BillingUsageResponse]:
        r"""Get billing usage information

        Retrieve billing usage metrics for your account and product environments,
        including storage, bandwidth, impressions, and transformations.

        If `year` is provided:
        - **Annual subscription**: Returns the single annual usage cycle that began in the specified year (if any).
        - **Monthly subscription**: Returns all monthly usage cycles that began in the specified year.

        If `year` is not provided:
        - Returns usage for the year in which the current active subscription period began.
        - If no active subscription exists, an empty list is returned.

        **Note**: Usage metrics are updated daily, so calling this endpoint once per day gives you the latest data.


        :param year: The year to retrieve billing usage for. Behavior depends on subscription type (see above).
        :param include_prodenv_breakdown: Whether to include usage details by product environment. **Default**: false.

        :param retries: Override the default retry configuration for this method
        :param server_url: Override the default server URL for this method
        :param timeout_ms: Override the default request timeout configuration for this method in milliseconds
        :param http_headers: Additional headers to set or replace on requests.
        """
        base_url = None
        url_variables = None
        if timeout_ms is None:
            timeout_ms = self.sdk_configuration.timeout_ms

        if server_url is not None:
            base_url = server_url
        else:
            base_url = self._get_url(base_url, url_variables)

        request = models.GetBillingUsageRequest(
            year=year,
            include_prodenv_breakdown=include_prodenv_breakdown,
        )

        req = self._build_request_async(
            method="GET",
            path="/v1_1/provisioning/accounts/{account_id}/billing_usage",
            base_url=base_url,
            url_variables=url_variables,
            request=request,
            request_body_required=False,
            request_has_path_params=True,
            request_has_query_params=True,
            user_agent_header="user-agent",
            accept_header_value="application/json",
            http_headers=http_headers,
            _globals=models.GetBillingUsageGlobals(
                account_id=self.sdk_configuration.globals.account_id,
            ),
            security=self.sdk_configuration.security,
            allow_empty_value=None,
            timeout_ms=timeout_ms,
        )

        if retries == UNSET:
            if self.sdk_configuration.retry_config is not UNSET:
                retries = self.sdk_configuration.retry_config

        retry_config = None
        if isinstance(retries, utils.RetryConfig):
            retry_config = (retries, ["429", "500", "502", "503", "504"])

        http_res = await self.do_request_async(
            hook_ctx=HookContext(
                config=self.sdk_configuration,
                base_url=base_url or "",
                operation_id="getBillingUsage",
                oauth2_scopes=None,
                security_source=get_security_from_env(
                    self.sdk_configuration.security, models.Security
                ),
            ),
            request=req,
            error_status_codes=["400", "401", "403", "404", "429", "4XX", "5XX"],
            retry_config=retry_config,
        )

        response_data: Any = None
        if utils.match_response(http_res, "200", "application/json"):
            return unmarshal_json_response(List[models.BillingUsageResponse], http_res)
        if utils.match_response(
            http_res, ["400", "401", "403", "404", "429"], "application/json"
        ):
            response_data = unmarshal_json_response(models.ErrorResponseData, http_res)
            raise models.ErrorResponse(response_data, http_res)
        if utils.match_response(http_res, "4XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)
        if utils.match_response(http_res, "5XX", "*"):
            http_res_text = await utils.stream_to_text_async(http_res)
            raise models.APIError("API error occurred", http_res, http_res_text)

        raise models.APIError("Unexpected response received", http_res)
