"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basesdk import BaseSDK
from .httpclient import AsyncHttpClient, ClientOwner, HttpClient, close_clients
from .sdkconfiguration import SDKConfiguration, ServerRegion
from .utils.logger import Logger, get_default_logger
from .utils.retries import RetryConfig
from cloudinary_account_provisioning import models, utils
from cloudinary_account_provisioning._hooks import SDKHooks
from cloudinary_account_provisioning.types import OptionalNullable, UNSET
import httpx
import importlib
import sys
from typing import Callable, Dict, List, Optional, TYPE_CHECKING, Union, cast
import weakref

if TYPE_CHECKING:
    from cloudinary_account_provisioning.accesskeys import AccessKeys
    from cloudinary_account_provisioning.billingusage import BillingUsage
    from cloudinary_account_provisioning.custompolicies import CustomPolicies
    from cloudinary_account_provisioning.effectivepolicies import EffectivePolicies
    from cloudinary_account_provisioning.principals import Principals
    from cloudinary_account_provisioning.productenvironments import ProductEnvironments
    from cloudinary_account_provisioning.public import Public
    from cloudinary_account_provisioning.roles import Roles
    from cloudinary_account_provisioning.systempolicies import SystemPolicies
    from cloudinary_account_provisioning.usergroups import UserGroups
    from cloudinary_account_provisioning.users import Users


class CldProvisioning(BaseSDK):
    r"""Cloudinary Account Provisioning API: Accounts with provisioning API access can create and manage their **product environments**, **users** and **user groups** using the RESTful Provisioning API.

    Provisioning API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).

    The API uses **Basic Authentication** over HTTPS. Your **Account API Key** and **Account API Secret** (previously referred to as **Provisioning API keys**) are used for the authentication. These credentials (as well as your ACCOUNT_ID) are located in the [Cloudinary Console](https://console.cloudinary.com/pm) under **Settings > Account API Keys**.

    The Provisioning API has dedicated SDKs for the following languages:

    * [JavaScript](https://github.com/cloudinary/account-provisioning-js)
    * [PHP](https://github.com/cloudinary/account-provisioning-php)
    * [Java](https://github.com/cloudinary/account-provisioning-java)

    Useful links:
    * [Provisioning API reference (Classic)](https://cloudinary.com/documentation/provisioning_api_1) (includes SDKs for additional languages)

    Accounts with Permissions API access can assign roles, made up of system policies, to control what principals (users, groups, and API keys) can do across the Cloudinary account and product environments. For more information about Cloudinary roles and permissions, see the [Role-based permissions](permissions_overview) guide.

    Permissions API access is available [upon request](https://cloudinary.com/contact?plan=enterprise) for accounts on an [Enterprise plan](https://cloudinary.com/pricing#pricing-enterprise).

    The API uses **Basic Authentication** over HTTPS. Your **Account API Key** and **Account API Secret** (previously referred to as **Provisioning API keys**) are used for the authentication. These credentials (as well as your ACCOUNT_ID) are located in the [Cloudinary Console](https://console.cloudinary.com/app/settings/account-api-keys) under **Settings > Account API Keys**.

    _**Important:**_

    _Cloudinary's **Roles and Permissions Management** is now available as a **Beta**. This is an early stage release, and while it's functional and ready for real-world testing, it's subject to change as we continue refining the experience based on what we learn, including your feedback.
    During the Beta period, core functionality is considered stable, though some APIs, scopes, or response formats may evolve._

    _**How you can help:**_

    * _Use Roles and Permissions Management in real projects, prototypes, or tests._
    * _Share feedback, issues, or ideas with our support team._

    _Thank you for exploring this early release and helping us shape these tools to best meet your needs._

    """

    product_environments: "ProductEnvironments"
    access_keys: "AccessKeys"
    users: "Users"
    r"""Manage the users for your account.

    https://cloudinary.com/documentation/provisioning_api#users - Learn more about users management.
    """
    user_groups: "UserGroups"
    billing_usage: "BillingUsage"
    public: "Public"
    r"""View shared Permissions system utilities, including the system roles and policies catalog, Cedar policy validation, and the Cedar schema. These endpoints are publicly accessible and don't require authentication.

    """
    system_policies: "SystemPolicies"
    custom_policies: "CustomPolicies"
    effective_policies: "EffectivePolicies"
    roles: "Roles"
    r"""All roles include one or more predefined **system policies**, and can be applied to principals to enforce these policies.

    You can **manage custom roles**, where you select the system policies.

    You can **view system roles**, which contain a fixed set of system policies and are provided by Cloudinary.

    """
    principals: "Principals"
    r"""View roles associated with a specified principal, and add or remove a role associated with a principal.

    """
    _sub_sdk_map = {
        "product_environments": (
            "cloudinary_account_provisioning.productenvironments",
            "ProductEnvironments",
        ),
        "access_keys": ("cloudinary_account_provisioning.accesskeys", "AccessKeys"),
        "users": ("cloudinary_account_provisioning.users", "Users"),
        "user_groups": ("cloudinary_account_provisioning.usergroups", "UserGroups"),
        "billing_usage": (
            "cloudinary_account_provisioning.billingusage",
            "BillingUsage",
        ),
        "public": ("cloudinary_account_provisioning.public", "Public"),
        "system_policies": (
            "cloudinary_account_provisioning.systempolicies",
            "SystemPolicies",
        ),
        "custom_policies": (
            "cloudinary_account_provisioning.custompolicies",
            "CustomPolicies",
        ),
        "effective_policies": (
            "cloudinary_account_provisioning.effectivepolicies",
            "EffectivePolicies",
        ),
        "roles": ("cloudinary_account_provisioning.roles", "Roles"),
        "principals": ("cloudinary_account_provisioning.principals", "Principals"),
    }

    def __init__(
        self,
        security: Optional[
            Union[models.Security, Callable[[], models.Security]]
        ] = None,
        account_id: Optional[str] = None,
        region: Optional[ServerRegion] = None,
        host: Optional[str] = None,
        server_idx: Optional[int] = None,
        server_url: Optional[str] = None,
        url_params: Optional[Dict[str, str]] = None,
        client: Optional[HttpClient] = None,
        async_client: Optional[AsyncHttpClient] = None,
        retry_config: OptionalNullable[RetryConfig] = UNSET,
        timeout_ms: Optional[int] = None,
        debug_logger: Optional[Logger] = None,
    ) -> None:
        r"""Instantiates the SDK configuring it with the provided parameters.

        :param security: The security details required for authentication
        :param account_id: Configures the account_id parameter for all supported operations
        :param region: Allows setting the region variable for url substitution
        :param host: Allows setting the host variable for url substitution
        :param server_idx: The index of the server to use for all methods
        :param server_url: The server URL to use for all methods
        :param url_params: Parameters to optionally template the server URL with
        :param client: The HTTP client to use for all synchronous methods
        :param async_client: The Async HTTP client to use for all asynchronous methods
        :param retry_config: The retry configuration to use for all supported methods
        :param timeout_ms: Optional request timeout applied to each operation in milliseconds
        """
        client_supplied = True
        if client is None:
            client = httpx.Client(follow_redirects=True)
            client_supplied = False

        assert issubclass(
            type(client), HttpClient
        ), "The provided client must implement the HttpClient protocol."

        async_client_supplied = True
        if async_client is None:
            async_client = httpx.AsyncClient(follow_redirects=True)
            async_client_supplied = False

        if debug_logger is None:
            debug_logger = get_default_logger()

        assert issubclass(
            type(async_client), AsyncHttpClient
        ), "The provided async_client must implement the AsyncHttpClient protocol."

        if server_url is not None:
            if url_params is not None:
                server_url = utils.template_url(server_url, url_params)
        server_defaults: List[Dict[str, str]] = [
            {
                "region": region or "api",
            },
            {
                "host": host or "api.cloudinary.com",
            },
        ]

        _globals = models.internal.Globals(
            account_id=utils.get_global_from_env(
                account_id, "CLOUDINARY_ACCOUNT_ID", str
            ),
        )

        BaseSDK.__init__(
            self,
            SDKConfiguration(
                client=client,
                client_supplied=client_supplied,
                async_client=async_client,
                async_client_supplied=async_client_supplied,
                globals=_globals,
                security=security,
                server_url=server_url,
                server_idx=server_idx,
                server_defaults=server_defaults,
                retry_config=retry_config,
                timeout_ms=timeout_ms,
                debug_logger=debug_logger,
            ),
            parent_ref=self,
        )

        hooks = SDKHooks()

        # pylint: disable=protected-access
        self.sdk_configuration.__dict__["_hooks"] = hooks

        self.sdk_configuration = hooks.sdk_init(self.sdk_configuration)

        weakref.finalize(
            self,
            close_clients,
            cast(ClientOwner, self.sdk_configuration),
            self.sdk_configuration.client,
            self.sdk_configuration.client_supplied,
            self.sdk_configuration.async_client,
            self.sdk_configuration.async_client_supplied,
        )

    def dynamic_import(self, modname, retries=3):
        for attempt in range(retries):
            try:
                return importlib.import_module(modname)
            except KeyError:
                # Clear any half-initialized module and retry
                sys.modules.pop(modname, None)
                if attempt == retries - 1:
                    break
        raise KeyError(f"Failed to import module '{modname}' after {retries} attempts")

    def __getattr__(self, name: str):
        if name in self._sub_sdk_map:
            module_path, class_name = self._sub_sdk_map[name]
            try:
                module = self.dynamic_import(module_path)
                klass = getattr(module, class_name)
                instance = klass(self.sdk_configuration, parent_ref=self)
                setattr(self, name, instance)
                return instance
            except ImportError as e:
                raise AttributeError(
                    f"Failed to import module {module_path} for attribute {name}: {e}"
                ) from e
            except AttributeError as e:
                raise AttributeError(
                    f"Failed to find class {class_name} in module {module_path} for attribute {name}: {e}"
                ) from e

        raise AttributeError(
            f"'{type(self).__name__}' object has no attribute '{name}'"
        )

    def __dir__(self):
        default_attrs = list(super().__dir__())
        lazy_attrs = list(self._sub_sdk_map.keys())
        return sorted(list(set(default_attrs + lazy_attrs)))

    def __enter__(self):
        return self

    async def __aenter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.client is not None
            and not self.sdk_configuration.client_supplied
        ):
            self.sdk_configuration.client.close()
        self.sdk_configuration.client = None

    async def __aexit__(self, exc_type, exc_val, exc_tb):
        if (
            self.sdk_configuration.async_client is not None
            and not self.sdk_configuration.async_client_supplied
        ):
            await self.sdk_configuration.async_client.aclose()
        self.sdk_configuration.async_client = None
